FROM asyoez/python3-nltk:latest

# pip install
RUN pip install ipython legal-doc-processing==1.2.1

# spacy
RUN python -m spacy download en_core_web_sm
RUN python -m nltk.downloader stopwords punkt

# app
WORKDIR /app
COPY . /app

# data
WORKDIR /data
COPY ./data /data

# boot
WORKDIR /
RUN python /app/utils/boot.py