FROM python:3.9-buster

# pip install
RUN pip install ipython legal-doc-processing==1.1.10

# workdir
WORKDIR /data

# copy the app
COPY ./data .

# workdir
WORKDIR /


# boot
# RUN python -c "import legal_doc_processing"
# RUN python -c "from legal_doc_processing.pr import read_PressRelease as rr; rr('./data/boot/press_release.txt) "
# RUN python -c "from legal_doc_processing.ld import read_LegalDoc as rr; rr('./data/boot/order.txt') "

