FROM python:3.9-buster

# pip install
RUN pip install ipython legal-doc-processing==1.1.11

# spacy
RUN python -m spacy download en_core_web_sm

# app
WORKDIR /app
COPY . /app

# data
WORKDIR /data
COPY ./data /data

# boot
WORKDIR /
# RUN python /app/utils/boot.py